-- Core tables for e-commerce warehouse
-- These are loaded from parquet files generated by seed_data.py

CREATE TABLE IF NOT EXISTS orders (
    order_id INTEGER PRIMARY KEY,
    order_date DATE NOT NULL,
    customer_id INTEGER NOT NULL,
    customer_type VARCHAR NOT NULL,
    channel VARCHAR NOT NULL,
    region VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    campaign VARCHAR NOT NULL,
    payment_type VARCHAR NOT NULL,
    order_total DOUBLE NOT NULL,
    order_status VARCHAR NOT NULL,
    is_cancelled BOOLEAN NOT NULL,
    is_refunded BOOLEAN NOT NULL,
    is_pending BOOLEAN NOT NULL,
    n_items INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items (
    item_id INTEGER PRIMARY KEY,
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DOUBLE NOT NULL,
    line_total DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    product_id INTEGER PRIMARY KEY,
    product_name VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    base_price DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
    customer_id INTEGER PRIMARY KEY,
    signup_date DATE NOT NULL,
    region VARCHAR NOT NULL,
    acquisition_channel VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
    payment_id INTEGER PRIMARY KEY,
    order_id INTEGER NOT NULL,
    payment_type VARCHAR NOT NULL,
    amount DOUBLE NOT NULL,
    payment_status VARCHAR NOT NULL,
    payment_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS channels (
    channel_id INTEGER PRIMARY KEY,
    channel_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS regions (
    region_id INTEGER PRIMARY KEY,
    region_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS campaigns (
    campaign_id INTEGER PRIMARY KEY,
    campaign_name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS refunds (
    refund_id INTEGER PRIMARY KEY,
    order_id INTEGER NOT NULL,
    refund_date DATE NOT NULL,
    refund_amount DOUBLE NOT NULL,
    reason VARCHAR NOT NULL
);
