"""Jinja2 templates for report generation."""

MARKDOWN_TEMPLATE = """# KPI Investigation Report

**Report ID:** {{ run_id }}
**Generated:** {{ generated_at }}
**KPI:** {{ kpi_name }}
**Anomaly Window:** {{ anomaly_start }} to {{ anomaly_end }}
**Baseline Window:** {{ baseline_start }} to {{ baseline_end }}

---

## 1. Executive Summary

{{ executive_summary }}

---

## 2. Incident Context

{{ incident_context }}

---

## 3. Metric Definition and Caveats

{% for doc in retrieved_docs %}
**{{ doc.section }}** ({{ doc.source }}):
{{ doc.content[:300] }}
{% if doc.content|length > 300 %}...{% endif %}

{% endfor %}

---

## 4. Investigation Plan

**Hypothesis:** {{ hypothesis }}

**Priority Dimensions:** {{ priority_dimensions | join(', ') }}

| Step | Action | Description |
|------|--------|-------------|
{% for step in plan_steps %}| {{ step.step_number }} | {{ step.action }} | {{ step.description }} |
{% endfor %}

---

## 5. SQL Evidence Summary

{% for result in sql_results %}
### Query: {{ result.query_id }}
- **Rows returned:** {{ result.row_count }}
- **Status:** {{ "Success" if result.success else "Failed: " + result.error }}
{% if result.success and result.data %}
| {% for col in result.columns %}{{ col }} | {% endfor %}
| {% for col in result.columns %}--- | {% endfor %}
{% for row in result.data[:10] %}| {% for col in result.columns %}{{ row[col] }} | {% endfor %}
{% endfor %}
{% if result.row_count > 10 %}*... {{ result.row_count - 10 }} more rows*{% endif %}
{% endif %}

{% endfor %}

---

## 6. Analytical Findings

{% for finding in findings %}
### {{ "Primary Finding" if finding.is_primary else "Secondary Finding" }}
{{ finding.description }}

**Confidence:** {{ finding.confidence }}

{% if finding.caveats %}
**Caveats:**
{% for caveat in finding.caveats %}- {{ caveat }}
{% endfor %}{% endif %}
{% endfor %}

### Contribution Analysis Details

{% for analysis in analysis_results %}
**{{ analysis.description }}**

| Slice | Baseline (daily) | Anomaly (daily) | Change | % Change | Contribution |
|-------|-------------------|-----------------|--------|----------|-------------|
{% for d in analysis.top_drivers[:8] %}| {{ d.slice_value }} | {{ "%.2f"|format(d.baseline_value) }} | {{ "%.2f"|format(d.anomaly_value) }} | {{ "%+.2f"|format(d.absolute_change) }} | {{ "%+.1f"|format(d.percent_change) }}% | {{ "%.1f"|format(d.contribution_pct) }}% |
{% endfor %}

{% if analysis.chart_path %}📊 Chart: [{{ analysis.chart_path | basename }}]({{ analysis.chart_path }}){% endif %}

{% endfor %}

---

## 7. Confidence and Limitations

**Overall Confidence:** {{ confidence }}

**Verification Checks:**

| Check | Result | Detail |
|-------|--------|--------|
{% for check in verification_checks %}| {{ check.check_name }} | {{ "✓" if check.passed else "✗" }} | {{ check.detail }} |
{% endfor %}

{% if unsupported_claims %}
**Unsupported Claims:**
{% for claim in unsupported_claims %}- {{ claim }}
{% endfor %}{% endif %}

{% if review_status != "not_required" %}
**Human Review:** {{ review_status }}
{% if review_reasons %}Trigger reasons: {{ review_reasons | join(', ') }}{% endif %}
{% endif %}

---

## 8. Final Root-Cause Assessment

{{ draft_conclusion }}

---

## 9. Suggested Follow-up Analyses

{% for suggestion in follow_ups %}- {{ suggestion }}
{% endfor %}

---

*Generated by Agentic KPI Root-Cause Analyst v{{ version }}*
"""

HTML_WRAPPER = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>KPI Investigation Report - {{ run_id }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px auto; max-width: 900px; line-height: 1.6; color: #333; }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        h2 { color: #2980b9; border-bottom: 1px solid #bdc3c7; padding-bottom: 5px; margin-top: 30px; }
        h3 { color: #7f8c8d; }
        table { border-collapse: collapse; width: 100%; margin: 15px 0; }
        th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
        th { background: #f8f9fa; font-weight: 600; }
        tr:nth-child(even) { background: #f8f9fa; }
        code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }
        .confidence-high { color: #27ae60; font-weight: bold; }
        .confidence-medium { color: #f39c12; font-weight: bold; }
        .confidence-low { color: #e74c3c; font-weight: bold; }
        .confidence-inconclusive { color: #95a5a6; font-weight: bold; }
        hr { border: none; border-top: 1px solid #eee; margin: 25px 0; }
        blockquote { border-left: 4px solid #3498db; margin-left: 0; padding-left: 15px; color: #555; }
    </style>
</head>
<body>
{{ content }}
</body>
</html>
"""
