"""Smoke tests for the full investigation graph in mock mode."""

import pytest

from agentic_kpi_analyst.config import Settings
from agentic_kpi_analyst.graph.graph import run_case
from agentic_kpi_analyst.models import ReviewStatus


@pytest.fixture(scope="module")
def settings() -> Settings:
    return Settings(
        llm_mode="mock",
        human_review_auto_approve=True,
    )


class TestGraphSmoke:
    """End-to-end smoke tests for the investigation workflow."""

    def test_run_case_ano005(self, settings: Settings) -> None:
        """Test full workflow on ANO-005 (payment failure)."""
        result = run_case("ANO-005", settings)

        assert result.run_id
        assert result.draft_conclusion
        assert len(result.evidence_registry) > 0
        assert len(result.analysis_results) > 0
        assert result.report is not None
        assert result.report.markdown_path

    def test_run_case_ano002(self, settings: Settings) -> None:
        """Test full workflow on ANO-002 (refund spike)."""
        result = run_case("ANO-002", settings)

        assert result.run_id
        assert result.draft_conclusion
        assert "refund" in result.draft_conclusion.lower() or "electronics" in result.draft_conclusion.lower()

    def test_sql_queries_execute(self, settings: Settings) -> None:
        """Verify SQL queries generated by mock LLM execute successfully."""
        result = run_case("ANO-005", settings)

        assert len(result.sql_results) > 0
        success_count = sum(1 for r in result.sql_results if r.success)
        assert success_count > 0, "At least one SQL query should succeed"

    def test_findings_are_produced(self, settings: Settings) -> None:
        """Verify findings are generated."""
        result = run_case("ANO-005", settings)

        assert len(result.findings) > 0
        primary = [f for f in result.findings if f.is_primary]
        assert len(primary) > 0, "Should have at least one primary finding"

    def test_verification_runs(self, settings: Settings) -> None:
        """Verify the verifier node runs and produces checks."""
        result = run_case("ANO-005", settings)

        assert result.verification is not None
        assert len(result.verification.checks) > 0

    def test_mock_mode_needs_no_api_key(self, settings: Settings) -> None:
        """Verify mock mode works without any API key configured."""
        mock_settings = Settings(
            llm_mode="mock",
            openai_api_key="",
            human_review_auto_approve=True,
        )
        result = run_case("ANO-001", mock_settings)
        assert result.run_id
        assert result.draft_conclusion
