"""Core data models for the KPI analyst system."""

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# --- Enums ---

class KPIName(str, Enum):
    """Supported KPI names."""
    GMV = "gmv"
    ORDER_COUNT = "order_count"
    AOV = "aov"
    CONVERSION_RATE = "conversion_rate"
    REFUND_RATE = "refund_rate"
    NEW_CUSTOMER_RATIO = "new_customer_ratio"
    REVENUE = "revenue"
    CANCELLATION_RATE = "cancellation_rate"


class Confidence(str, Enum):
    """Confidence levels for findings."""
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INCONCLUSIVE = "inconclusive"


class ReviewStatus(str, Enum):
    """Human review status."""
    NOT_REQUIRED = "not_required"
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


class ReviewTriggerReason(str, Enum):
    """Reasons for triggering human review."""
    LOW_CONFIDENCE = "low_confidence"
    SQL_VALIDATION_FAILURE = "sql_validation_failure"
    WEAK_EVIDENCE = "weak_evidence"
    COST_EXCEEDED = "cost_exceeded"


# --- Anomaly Case ---

class AnomalyCase(BaseModel):
    """A labeled anomaly case for investigation or evaluation."""
    case_id: str
    kpi_name: KPIName
    affected_start_date: date
    affected_end_date: date
    description: str
    expected_primary_cause: str
    expected_secondary_factors: list[str] = Field(default_factory=list)
    recommended_dimensions: list[str] = Field(default_factory=list)
    should_trigger_human_review: bool = False


# --- Investigation Request ---

class InvestigationRequest(BaseModel):
    """Input to the investigation workflow."""
    request_id: str
    kpi_name: KPIName
    start_date: date
    end_date: date
    description: str = ""
    baseline_start_date: date | None = None
    baseline_end_date: date | None = None
    case_id: str | None = None  # links to AnomalyCase if from eval


# --- Retrieved Context ---

class RetrievedDoc(BaseModel):
    """A document chunk retrieved from the knowledge base."""
    source: str
    section: str
    content: str
    relevance_score: float = 0.0


# --- Investigation Plan ---

class InvestigationStep(BaseModel):
    """A single step in the investigation plan."""
    step_number: int
    action: str  # e.g. "query_sql", "analyze_dimension", "compare_baseline"
    description: str
    dimensions: list[str] = Field(default_factory=list)
    sql_hint: str = ""


class InvestigationPlan(BaseModel):
    """Plan generated by the planner node."""
    hypothesis: str
    steps: list[InvestigationStep]
    priority_dimensions: list[str]


# --- SQL ---

class SQLQuery(BaseModel):
    """A generated SQL query with metadata."""
    query_id: str
    sql: str
    purpose: str
    target_view: str = ""


class SQLValidationResult(BaseModel):
    """Result of SQL validation."""
    is_valid: bool
    errors: list[str] = Field(default_factory=list)
    sanitized_sql: str = ""


class SQLExecutionResult(BaseModel):
    """Result of SQL execution."""
    query_id: str
    success: bool
    row_count: int = 0
    columns: list[str] = Field(default_factory=list)
    data: list[dict[str, Any]] = Field(default_factory=list)
    error: str = ""
    execution_time_ms: float = 0.0


# --- Analysis ---

class DimensionContribution(BaseModel):
    """Contribution of a dimension slice to KPI movement."""
    dimension: str
    slice_value: str
    baseline_value: float
    anomaly_value: float
    absolute_change: float
    percent_change: float
    contribution_pct: float  # how much of total change this slice explains


class AnalysisResult(BaseModel):
    """Output of Python analysis."""
    analysis_type: str  # "contribution", "slice_comparison", "baseline_comparison"
    description: str
    top_drivers: list[DimensionContribution] = Field(default_factory=list)
    summary_stats: dict[str, float] = Field(default_factory=dict)
    chart_path: str = ""
    table_data: list[dict[str, Any]] = Field(default_factory=list)


# --- Evidence ---

class EvidenceItem(BaseModel):
    """A piece of evidence supporting or refuting a finding."""
    evidence_id: str
    source_type: str  # "sql_result", "analysis", "metric_definition", "business_rule"
    source_ref: str  # query_id, analysis_type, doc source
    description: str
    supports_conclusion: bool = True
    strength: Confidence = Confidence.MEDIUM


# --- Findings ---

class Finding(BaseModel):
    """A root-cause finding with supporting evidence."""
    finding_id: str
    description: str
    confidence: Confidence
    evidence_ids: list[str] = Field(default_factory=list)
    is_primary: bool = False
    caveats: list[str] = Field(default_factory=list)


# --- Verification ---

class VerificationCheck(BaseModel):
    """A single verification check result."""
    check_name: str
    passed: bool
    detail: str


class VerificationResult(BaseModel):
    """Output of the verifier node."""
    overall_supported: bool
    checks: list[VerificationCheck] = Field(default_factory=list)
    unsupported_claims: list[str] = Field(default_factory=list)
    suggested_confidence: Confidence = Confidence.MEDIUM
    needs_human_review: bool = False
    review_reasons: list[ReviewTriggerReason] = Field(default_factory=list)


# --- Report ---

class ReportMetadata(BaseModel):
    """Metadata for a generated report."""
    report_id: str
    case_id: str | None = None
    generated_at: datetime
    markdown_path: str = ""
    html_path: str = ""
    json_path: str = ""


# --- Evaluation ---

class CaseEvalResult(BaseModel):
    """Evaluation result for a single anomaly case."""
    case_id: str
    primary_cause_hit: bool
    top_k_hit: bool = False
    sql_success_rate: float = 0.0
    evidence_sufficient: bool = False
    unsupported_claim_count: int = 0
    human_review_triggered: bool = False
    runtime_seconds: float = 0.0
    predicted_primary_cause: str = ""
    confidence: Confidence = Confidence.INCONCLUSIVE


class EvalSummary(BaseModel):
    """Aggregate evaluation metrics across all cases."""
    total_cases: int
    primary_hit_rate: float
    top_k_hit_rate: float
    avg_sql_success_rate: float
    evidence_sufficiency_rate: float
    avg_unsupported_claims: float
    human_review_trigger_rate: float
    avg_runtime_seconds: float
    per_case: list[CaseEvalResult] = Field(default_factory=list)
